# Analytics Service - Specific Values
serviceName: analytics-service

image:
  repository: us-central1-docker.pkg.dev/fiap-502903/analytics-service/analytics-service
  tag: "42d452a59522af2676493abfc94e67103664d359"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8005"
  prometheus.io/path: "/metrics"

service:
  port: 8080
  targetPort: 8005

ingress:
  hosts:
    - host: analytics.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: analytics-tls
      hosts:
        - analytics.example.com

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "staging"
  - name: PORT
    value: "8005"
  - name: GCP_PROJECT_ID
    value: "fiap-502903"
  - name: GCP_PUBSUB_TOPIC
    value: "toggle-master-analytics-events"
  - name: GCP_PUBSUB_SUBSCRIPTION
    value: "toggle-master-analytics-worker-sub"
  - name: GCP_FIRESTORE_COLLECTION
    value: "ToggleMasterAnalytics"

database:
  enabled: false

livenessProbe:
  httpGet:
    path: /health
    port: 8005

readinessProbe:
  httpGet:
    path: /health
    port: 8005
