# Auth Service - Specific Values
serviceName: auth-service

image:
  repository: us-central1-docker.pkg.dev/fiap-502903/auth-service/auth-service

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8001"
  prometheus.io/path: "/metrics"

service:
  port: 8001
  targetPort: 8001

ingress:
  enabled: false

autoscaling:
  minReplicas: 1
  maxReplicas: 3

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "staging"
  - name: PORT
    value: "8001"
  - name: MASTER_KEY
    value: "admin-secreto-123"

database:
  enabled: true
  secretName: auth-db-credentials
  createSecret: false
  host: postgres.db-infra.svc.cluster.local
  port: 5432
  name: auth_db
  user: auth_service

livenessProbe:
  httpGet:
    path: /health
    port: 8001

readinessProbe:
  httpGet:
    path: /health
    port: 8001
