# Evaluation Service - Specific Values
serviceName: evaluation-service

image:
  repository: us-central1-docker.pkg.dev/fiap-502903/evaluation-service/evaluation-service

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

service:
  port: 8080
  targetPort: 8004

ingress:
  hosts:
    - host: evaluation.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: evaluation-tls
      hosts:
        - evaluation.example.com

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "staging"
  - name: PORT
    value: "8004"
  - name: GCP_PROJECT_ID
    value: "fiap-502903"
  - name: QUEUE_PROVIDER
    value: "pubsub"
  - name: PUBSUB_TOPIC
    value: "toggle-master-analytics-events"  
  - name: REDIS_URL
    value: "redis://redis.default.svc.cluster.local:6379"
  - name: FLAG_SERVICE_URL
    value: "http://flag-service.default.svc.cluster.local:8002"
  - name: TARGETING_SERVICE_URL
    value: "http://target-service.default.svc.cluster.local:8003"

livenessProbe:
  httpGet:
    path: /health
    port: 8004

readinessProbe:
  httpGet:
    path: /health
    port: 8004

# Message Queue Configuration
messageQueue:
  enabled: true
  type: pubsub
  projectId: fiap-502903
