# Flag Service - Specific Values
serviceName: flag-service

image:
  repository: us-central1-docker.pkg.dev/fiap-502903/flag-service/flag-service

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8002"
  prometheus.io/path: "/metrics"

service:
  port: 8002
  targetPort: 8002

ingress:
  hosts:
    - host: flags.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: flag-tls
      hosts:
        - flags.example.com

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "staging"
  - name: PORT
    value: "8002"
  - name: GCP_PROJECT_ID
    value: "fiap-502903"

database:
  enabled: true
  secretName: flag-db-credentials
  createSecret: false
  host: postgres.db-infra.svc.cluster.local
  port: 5432
  name: flag_db
  user: flag_service

livenessProbe:
  httpGet:
    path: /health
    port: 8002

readinessProbe:
  httpGet:
    path: /health
    port: 8002
