apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Starts first
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "45.28.0"
    helm:
      values: |
        prometheus:
          enabled: true
          prometheusSpec:
            retention: 1d
            storageSpec:
              emptyDir:
                medium: Memory
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi

        grafana:
          enabled: true
          defaultDashboardsEnabled: true
          adminPassword: admin
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          service:
            type: ClusterIP
            port: 3000
            targetPort: 3000
          grafana.ini:
            server:
              root_url: http://localhost:3000
          
          # Enables the sidecar to automatically discover ConfigMap dashboards
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
            datasources:
              enabled: true

          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-operated.monitoring.svc.cluster.local:9090
                  access: proxy
                  editable: true
                  isDefault: false
                - name: Loki
                  type: loki
                  url: http://loki-stack.monitoring.svc.cluster.local:3100
                  access: proxy
                  editable: true
                  isDefault: false

        alertmanager:
          enabled: true
          alertmanagerSpec:
            retention: 24h
            storage:
              emptyDir:
                medium: Memory