apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-api-key
  namespace: default
type: Opaque
stringData:
    SERVICE_API_KEY: "tm_key_61eb91356c84ab128f961ae08cf18dec14cca5665953c2a75a6dfe375bd3b3dd"